### ISSUE TITLE
Error installing on MacOSX -  Failed at the node-tensorflow@0.0.1 _preinstall script 'git submodule update --init --recursive && ./tools/build.sh'.

### ISSUE THREAD

**Issue by csanz** [nikhilk/node-tensorflow#12]
I get errors when trying to install / run 

_npm run _preinstall_

 Failed at the node-tensorflow@0.0.1 _preinstall script 'git submodule update --init --recursive && ./tools/build.sh'.

**Here is the output on a gist** 

https://gist.github.com/csanz/717a68a8c7c1eb96f39e2799ff330622

**Here is the pasted version**

$ npm run _preinstall

> node-tensorflow@0.0.1 _preinstall /Users/csanz/Apps/node-tensorflow
> git submodule update --init --recursive && ./tools/build.sh

HEAD is now at c4207090d Merge pull request #1050 from chemelnucfin/fixcomparison.
patching file tensorflow/cc/BUILD
No GPU support will be enabled for TensorFlow
Configuration finished
./tools/build.sh: line 9: bazel: command not found
./tools/build.sh: line 10: bazel: command not found
./tools/build.sh: line 11: bazel: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-tensorflow@0.0.1 _preinstall: `git submodule update --init --recursive && ./tools/build.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-tensorflow@0.0.1 _preinstall script 'git submodule update --init --recursive && ./tools/build.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-tensorflow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     git submodule update --init --recursive && ./tools/build.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-tensorflow
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-tensorflow
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/csanz/.npm/_logs/2017-04-10T16_26_52_378Z-debug.log
$ npm -v
4.4.4
$ node -v
v6.10.2

Thoughts? Am I doing something wrong? I'm starting to look into it deeper, but I just wanted to posted this just in case this was already solved by someone.

**Comment by nikhilk** [comment]
Made a fix via 20aa73f246a8e27752f97d8a3e95c67507daa17b but I need to fully verify, for which I need to publish an npm package and run through an npm install.

**Comment by ralphtheninja** [comment]
@nikhilk Fyi, you can do pre-releases in case you want to release a version that shouldn't become the new latest version.

`npm version prepatch` or `npm version preminor` or `npm version premajor`

**Comment by nikhilk** [comment]
Ah, good to know.

**Comment by ralphtheninja** [comment]
And you can use tags when publishing as well to prevent changing the default module, e.g. `npm publish --tag download-test`

**Comment by nikhilk** [comment]
This should now be fixed with 0.6.4 published to npmjs as the *tensorflow* npm module ... @ralphtheninja or @csanz if you could validate that would be awesome.

**Comment by ralphtheninja** [comment]
Works well!
