### ISSUE TITLE
Free up one of the two npm packages

### ISSUE THREAD

**Issue by ZECTBynmo** [nikhilk/node-tensorflow#6]
Why does this repo need to be published under tensorflow and node-tensorflow? Seems like it'd be better to allow for competing implementations (especially since development seems to have stalled here).

https://www.npmjs.com/package/node-tensorflow
https://www.npmjs.com/package/tensorflow

**Comment by goatandsheep** [comment]
I think node-tensorflow is dead, but tensorflow is being updated

**Comment by ralphtheninja** [comment]
@nikhilk I think you hould consider removing the `node-` prefix from the repository name since you are publishing it as `tensorflow` anyway.

**Comment by nikhilk** [comment]
I added `node-` to the repo name as it would conflict if you had a branch of the tensorflow repo (which I did at some point for a fork containing blaze targets to build tensorflow libs).

**Comment by goatandsheep** [comment]
Perhaps a better idea is to change the readme in the description of npm/node-tensorflow to forward to npm/tensorflow
