### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by abdulhannanali** [nikhilk/node-tensorflow#7]
Assuming, this project's code is truly for open source purposes, this needs a LICENSE. Please, decide a LICENSE and then include it in this project. :smile:

**Comment by lucaspiller** [comment]
The [package.json says that it is licensed under Apache 2.0](https://github.com/nikhilk/node-tensorflow/blob/0b9a8f4ebecdf65772bbd39866f562a55baa8c80/package.json#L23), but yes it would be good to have an explicit LICENSE file in the repository too.

**Comment by abdulhannanali** [comment]
@lucaspiller definitely, a good measure to take

**Comment by nikhilk** [comment]
Finally addressed in #67d9a02  :)
